package api

// Remaining event types: 3653,3774,4738
var cacheTypes = map[string]int{
	"Traditional":            2,
	"Multi":                  3,
	"Virtual":                4,
	"Letterbox":              5,
	"Event":                  6,
	"Unknown":                8,
	"Webcam":                 11,
	"CITO":                   13,
	"Earthcache":             137,
	"Mega":                   453,
	"GPS Adventures Exhibit": 1304,
	"Wherigo":                1858,
	"Giga":                   7005,
}

var cacheSizes = map[string]int{
	"Micro":   2,
	"Regular": 3,
	"Large":   4,
	"Other":   6,
	"Small":   8,
}

var cacheAttributes = map[string]int{
	"Dogs":                            1,
	"Access or parking fee":           2,
	"Climbing gear":                   3,
	"Boat":                            4,
	"Scuba gear":                      5,
	"Recommended for kids":            6,
	"Takes less than an hour":         7,
	"Scenic view":                     8,
	"Significant hike":                9,
	"Difficult climbing":              10,
	"May require wading":              11,
	"May require swimming":            12,
	"Available at all times":          13,
	"Recommended at night":            14,
	"Available during winter":         15,
	"Cacti nearby":                    16, //retired, https://www.geocaching.com/geocache/GC684
	"Poison plants":                   17,
	"Dangerous Animals":               18,
	"Ticks":                           19,
	"Abandoned mines":                 20,
	"Cliff / falling rocks":           21,
	"Hunting":                         22,
	"Dangerous area":                  23,
	"Wheelchair accessible":           24,
	"Parking available":               25,
	"Public transportation":           26,
	"Drinking water nearby":           27,
	"Public restrooms nearby":         28,
	"Telephone nearby":                29,
	"Picnic tables nearby":            30,
	"Camping available":               31,
	"Bicycles":                        32,
	"Motorcycles":                     33,
	"Quads":                           34,
	"Off-road vehicles":               35,
	"Snowmobiles":                     36,
	"Horses":                          37,
	"Campfires":                       38,
	"Thorns":                          39,
	"Stealth required":                40,
	"Stroller accessible":             41,
	"Needs maintenance":               42,
	"Watch for livestock":             43,
	"Flashlight required":             44,
	"Truck Driver/RV":                 46,
	"Field Puzzle":                    47,
	"UV Light Required":               48,
	"Snowshoes":                       49,
	"Cross Country Skis":              50,
	"Special Tool Required":           51,
	"Night Cache":                     52,
	"Park and Grab":                   53,
	"Abandoned Structure":             54,
	"Short hike (less than 1km)":      55,
	"Medium hike (1km-10km)":          56,
	"Long Hike (+10km)":               57,
	"Fuel Nearby":                     58,
	"Food Nearby":                     59,
	"Wireless Beacon":                 60,
	"Partnership cache":               61,
	"Seasonal Access":                 62,
	"Tourist Friendly":                63,
	"Tree Climbing":                   64,
	"Front Yard (Private Residence)":  65,
	"Teamwork Required":               66,
	"GeoTour":                         67,
	"Bonus cache":                     69,
	"Power trail":                     70,
	"Challenge Cache":                 71,
	"Geocaching.com solution checker": 72,
}
